### ISSUE TITLE
Blender Models

### ISSUE THREAD

**Issue by terorie** [aero-extrem/aero-extrem#2]
Models für Flugzeug, Objekte, Terrain…

**Comment by terorie** [comment]
Ich erstelle das Model für den Eurofighter Typhoon

**Comment by oldfrizt** [comment]
Mit Texturen?

**Comment by terorie** [comment]
Ich kenne mich nicht mit UV Mapping aus, kannst du mir da helfen? Ich lad die .blend auf jeden Fall hoch.

**Comment by terorie** [comment]
Ich bin zu blöd, kannst du die [Datei auf blender-dev](https://github.com/aero-extrem/aero-extrem/blob/c75ebcba07d1eb5d93642d55942eb8580d65a5b8/core/assets/jet_test1.blend) fixen? Ich mach jetzt lieber den Code.

**Comment by terorie** [comment]
@oldfrizt hat die [Sukhoi T-50](https://github.com/aero-extrem/aero-extrem/blob/master/core/assets-dev/T-50.blend) hochgeladen.
Das reicht fürs erste.
